### ISSUE TITLE
connections form ux improved.

### ISSUE THREAD

**Issue by adriagarrido** [adriagarrido/magento-wsc-lite#7]
At this moment the connection form remove a lot of space to the request form. I like to suggest a different actions for the form depending of the state of the select.
- 'New Connection' : Show the form and save button.
- Connection selected: Don't show the form, show edit button.
  - click on edit: show form and replace edit button for save and delete buttons.
    - click on save: go to Connection selected state.
    - click on delete: go to 'New Connection' state.

What do you think?

**Comment by frankycan** [comment]
Implemented at #10
